=== djiby26/xml_class_project/xml/examen.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT examen (titre,date,questions)>
	<!ATTLIST examen codeCours NMTOKEN #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT date EMPTY >
	<!ATTLIST date 
		mois (Janvier|Fevrier|Mars|Avril|Mai|Juin|Juillet|Aout|Septembre|Octobre|Novenmbre|Decembre) #REQUIRED
		annee NMTOKEN #REQUIRED
	>

<!ELEMENT questions (question,question,question,question,question,question?)>
<!ELEMENT question (partie+)>
<!ELEMENT partie (#PCDATA|partie)*>

=== djiby26/xml_class_project/xml/examen.xml
<?xml version="1.0"?>
<!DOCTYPE examen SYSTEM "examen.dtd">
<examen codeCours="1">
	<titre>
		XML:Syntaxe-DTD
	</titre>
	<date mois="Janvier" annee="2019" />
	<questions>
		<question>
			<partie>
				A.Quel est le nom de l'élément-racine? 
				B.Quel est le contenu de l'élément «president»? 
				C.Quel est le contenu de l'élément «comptable»? 
				D.Quel est le contenu de l'élément «adjoint»? 
				E.Combien d'éléments «president» peut contenir un element «compagnie»?
			</partie>
			
		</question>
		<question>
			
			<partie>
				A.Quel est le nom de l'élément-racine? 
				B.Quel est le contenu de l'élément «president»? 
				C.Quel est le contenu de l'élément «comptable»? 
				D.Quel est le contenu de l'élément «adjoint»? 
				E.Combien d'éléments «president» peut contenir un element «compagnie»?
			</partie>
		
		</question>
		<question>
			
				<partie>
					A.Quel est le nom de l'élément-racine? 
					B.Quel est le contenu de l'élément «president»? 
					C.Quel est le contenu de l'élément «comptable»? 
					D.Quel est le contenu de l'élément «adjoint»? 
					E.Combien d'éléments «president» peut contenir un element «compagnie»?
				</partie>
			
		</question>
		<question>
			
				Au Cinéma!
				Les Brigades du Tigre 
				- Policier (2h 5min)
				- De Jérôme Cornuau
				- VF (en Français)
				- Avec: C. Cornillac, D. Kruger, E. Baer
				- Année: 2005
				- Presse : 3/5 Spectateurs : 4/5
				Les aventures du commissaire Valentin et des inspecteurs Terrasson et Pujol, 
				membres des Brigades mobiles, corps spécial de la police française créé avant 
				la Première Guerre mondiale.
				Mer, Sam : 14:00 | 16:40 | 19:40 | 22:10
				Jeu, Ven, Lun, Mar : 14:00 | 19:40 | 22:10
				Dim : 10:20 | 14:00 | 16:40 | 20:20
				<partie>
					Dans cet exercice on se propose de concevoir un système permettant de publier le programme d'un 
					cinéma sur Internet. Le programme est constitué du descriptif de chaque film à l'affiche pendant la 
					semaine. Comme dans l'exemple, ci-après, chaque film est décrit par son titre, sa durée, son genre, son 
					réalisateur, ses acteurs, année de production sa langue de diffusion ainsi que par un court paragraphe 
					décrivant l'intrigue. Cette description est complétée par la liste des horaires de projection
				</partie>
				<partie>
					Proposer un arbre XML pour représenter le film décrit ci-dessus (Les brigades du tigres)
				</partie>
				
			
		</question>
		<question>
			
				Au Cinéma!
				Les Brigades du Tigre 
				- Policier (2h 5min)
				- De Jérôme Cornuau
				- VF (en Français)
				- Avec: C. Cornillac, D. Kruger, E. Baer
				- Année: 2005
				- Presse : 3/5 Spectateurs : 4/5
				Les aventures du commissaire Valentin et des inspecteurs Terrasson et Pujol, 
				membres des Brigades mobiles, corps spécial de la police française créé avant 
				la Première Guerre mondiale.
				Mer, Sam : 14:00 | 16:40 | 19:40 | 22:10
				Jeu, Ven, Lun, Mar : 14:00 | 19:40 | 22:10
				Dim : 10:20 | 14:00 | 16:40 | 20:20
				<partie>
					Dans cet exercice on se propose de concevoir un système permettant de publier le programme d'un 
					cinéma sur Internet. Le programme est constitué du descriptif de chaque film à l'affiche pendant la 
					semaine. Comme dans l'exemple, ci-après, chaque film est décrit par son titre, sa durée, son genre, son 
					réalisateur, ses acteurs, année de production sa langue de diffusion ainsi que par un court paragraphe 
					décrivant l'intrigue. Cette description est complétée par la liste des horaires de projection
				</partie>
				<partie>
					Proposer un arbre XML pour représenter le film décrit ci-dessus (Les brigades du tigres)
				</partie>
				<partie>
					
				</partie>
			
		</question>
	</questions>
</examen>

=== djiby26/xml_class_project/xml/examplxml.xml
<?xml version="1.0"?>
<!DOCTYPE examen SYSTEM "examen.dtd">
<examen codeCours="2">
  <titre>Data Mining</titre>
  <date mois="Novembre" annee="2021"/>
  <questions>
    <question>
      <partie> SI on nous demande de calculer un gain avec un attribut donn&#xE9;,  Ici, income level prend 3 valeurs : Low, Medium, High     Gain(T,I) = E(T) - (2/10E(L)+E6/10(M)+2/10E(H))</partie>
      <partie>Dans ce cas on 14 observations, 9 oui et 5 non. Pour d&#xE9;terminer si on a oui ou non dans notre noeud, on prend celui qui est le plus grand. Exog&#xE8;ne =&gt; aidant &#xE0; la pr&#xE9;diction</partie>
      <partie> interpr&#xE9;ter un arbre revient &#xE0; dire il y a combien de noeuds. On explique jusqu'&#xE0; nsplit=2. On a les variables qualitatives et les variables quantitatives. Les variables quantitatives peuvent &#xEA;tre continues ou discr&#xE8;tes. </partie>
      <partie>    SI on nous demande de calculer un gain avec un attribut donn&#xE9;,  Ici, income level prend 3 valeurs : Low, Medium, High     Gain(T,I) = E(T) - (2/10E(L)+E6/10(M)+2/10E(H))</partie>
    </question>
    <question>
      <partie>Dans ce cas on 14 observations, 9 oui et 5 non. Pour d&#xE9;terminer si on a oui ou non dans notre noeud, on prend celui qui est le plus grand. Exog&#xE8;ne =&gt; aidant &#xE0; la pr&#xE9;diction</partie>
      <partie> interpr&#xE9;ter un arbre revient &#xE0; dire il y a combien de noeuds. On explique jusqu'&#xE0; nsplit=2. On a les variables qualitatives et les variables quantitatives. Les variables quantitatives peuvent &#xEA;tre continues ou discr&#xE8;tes. </partie>
      <partie> : La variable est discr&#xE8;te, l'arbre n'est pas binaire.         - B : La variable est continue et on a fait la discr&#xE9;ditation.         - C : La variable est discr&#xE8;te, l'arbre est binaire.         </partie>
      <partie>    SI on nous demande de calculer un gain avec un attribut donn&#xE9;,  Ici, income level prend 3 valeurs : Low, Medium, High     Gain(T,I) = E(T) - (2/10E(L)+E6/10(M)+2/10E(H))</partie>
    </question>
    <question>
      <partie>Dans ce cas on 14 observations, 9 oui et 5 non. Pour d&#xE9;terminer si on a oui ou non dans notre noeud, on prend celui qui est le plus grand. Exog&#xE8;ne =&gt; aidant &#xE0; la pr&#xE9;diction</partie>
      <partie> interpr&#xE9;ter un arbre revient &#xE0; dire il y a combien de noeuds. On explique jusqu'&#xE0; nsplit=2. On a les variables qualitatives et les variables quantitatives. Les variables quantitatives peuvent &#xEA;tre continues ou discr&#xE8;tes. </partie>
      <partie> : La variable est discr&#xE8;te, l'arbre n'est pas binaire.         - B : La variable est continue et on a fait la discr&#xE9;ditation.         - C : La variable est discr&#xE8;te, l'arbre est binaire.         </partie>
      <partie>    SI on nous demande de calculer un gain avec un attribut donn&#xE9;,  Ici, income level prend 3 valeurs : Low, Medium, High     Gain(T,I) = E(T) - (2/10E(L)+E6/10(M)+2/10E(H))</partie>
    </question>
    <question>
      <partie>Dans ce cas on 14 observations, 9 oui et 5 non. Pour d&#xE9;terminer si on a oui ou non dans notre noeud, on prend celui qui est le plus grand. Exog&#xE8;ne =&gt; aidant &#xE0; la pr&#xE9;diction</partie>
      <partie> interpr&#xE9;ter un arbre revient &#xE0; dire il y a combien de noeuds. On explique jusqu'&#xE0; nsplit=2. On a les variables qualitatives et les variables quantitatives. Les variables quantitatives peuvent &#xEA;tre continues ou discr&#xE8;tes. </partie>
      <partie> : La variable est discr&#xE8;te, l'arbre n'est pas binaire.         - B : La variable est continue et on a fait la discr&#xE9;ditation.         - C : La variable est discr&#xE8;te, l'arbre est binaire.         </partie>
      <partie>    SI on nous demande de calculer un gain avec un attribut donn&#xE9;,  Ici, income level prend 3 valeurs : Low, Medium, High     Gain(T,I) = E(T) - (2/10E(L)+E6/10(M)+2/10E(H))</partie>
    </question>
    <question>
      <partie>Dans ce cas on 14 observations, 9 oui et 5 non. Pour d&#xE9;terminer si on a oui ou non dans notre noeud, on prend celui qui est le plus grand. Exog&#xE8;ne =&gt; aidant &#xE0; la pr&#xE9;diction</partie>
      <partie> interpr&#xE9;ter un arbre revient &#xE0; dire il y a combien de noeuds. On explique jusqu'&#xE0; nsplit=2. On a les variables qualitatives et les variables quantitatives. Les variables quantitatives peuvent &#xEA;tre continues ou discr&#xE8;tes. </partie>
      <partie> : La variable est discr&#xE8;te, l'arbre n'est pas binaire.         - B : La variable est continue et on a fait la discr&#xE9;ditation.         - C : La variable est discr&#xE8;te, l'arbre est binaire.         </partie>
      <partie>    SI on nous demande de calculer un gain avec un attribut donn&#xE9;,  Ici, income level prend 3 valeurs : Low, Medium, High     Gain(T,I) = E(T) - (2/10E(L)+E6/10(M)+2/10E(H))----</partie>
    </question>
  </questions>
</examen>
